main:
  push:
    - imports: https://cnb.cool/zinc233/secrets/-/blob/main/tencent/edgeone.env
    
      stages:
        - name: Build Current Project
          image: node:25
          script: node -v && npm install && npm run generate:sitemap && npm run build

        - name: Deploy to EdgeOne Pages
          image: tencentcom/deploy-eopages:latest
          script: |
            edgeone pages deploy dist -n tool-site -t $EDGEONE_API_TOKEN